fint:
  org-id: fintlabs.no
  application-id: fint-kontroll-user-service
  kontroll:
    opa:
      url: http://fint-kontroll-opa:8181/v1/data/accessmanagement
    authorization:
      authorized-role: https://role-catalog.vigoiks.no/vigo/kontroll/user
      authorized-org-id: vigo.no
    user:
      publishing:
        initial-delay: PT1M
        fixed-delay: PT5M
      days-before-start-employee: 10
      days-before-start-student: 5

novari:
  cache:
    defaultCacheEntryTimeToLive: "604800000ms"
    defaultCacheHeapSize: 1000000

  kafka:
    topic:
      org-id: fintlabs-no                 # TODO: MÅ BORT NÅR DEN REGISTRERES I KUSTOMIZE OVERLAY
      domain-context: kontroll
    application-id: ${fint.application-id}
    default-replicas: 1

spring:
  application:
    name: fint-kontroll-user-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
  flyway:
    enabled: true
    locations: classpath:db/migration
  profiles:
    include:
      - observability
      - db
logging:
  level:
    root: INFO
    org.apache.kafka.clients: WARN
    org.apache.kafka.common: WARN
    org.apache.kafka.clients.consumer: WARN
    org.apache.kafka.clients.producer: WARN
    org.springframework.kafka: WARN
    no.novari.kafka: WARN
    no.novari.cache.ehcache.FintEhCacheEventLogger: WARN

jobs:
  delete-user:
    interval-cron: "0 0 2 * * MON"
    deleted-since-days: 30
