create table usersnew
(
    id                           bigint generated by default as identity primary key,
    resourceid                   varchar(255) not null unique,
    firstname                    varchar(255),
    lastname                     varchar(255),
    usertype                     varchar(255),
    username                     varchar(255),
    identityprovideruserobjectid uuid,
    mainorganisationunitname     varchar(255),
    mainorganisationunitid       varchar(255),
    email                        varchar(255),
    managerref                   varchar(255),
    status                       varchar(255) not null,
    statuschanged                timestamp,
    validfrom                    timestamp,
    validto                      timestamp,
    createddate                  timestamp,
    modifieddate                 timestamp
);

create table user_organisation_unit_ids
(
    user_id               bigint not null references usersnew,
    organisation_unit_ids varchar(255)
);
