apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-kontroll-user-service
  namespace: fintlabs-no
labels:
  app.kubernetes.io/name: fint-kontroll-user-service
  app.kubernetes.io/instance: fint-kontroll-user-service_fintlabs_no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-kontroll
  fintlabs.no/team: bas
  fintlabs.no/org-id: fintlabs.no
spec:
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-kontroll-user-service:latest
  imagePullPolicy: Always
  url:
    hostname: kontroll.vigo.no
    basePath: /beta/fintlabs-no
  ingress:
    enabled: true
    basePath: /beta/fintlabs-no/api
    middlewares:
      - fint-kontroll-sso
  kafka:
    enabled: true
    acls:
      - topic: 'fintlabs-no.kontroll.*'
        permission: read
      - topic: 'fintlabs-no.kontroll.*'
        permission: admin
  database:
    database: fint-kontroll
  env:
    - name: fint.kontroll.authorization.authorized-role
      value: "0 - https://role-catalog.vigoiks.no/vigo/kontroll/user"
    - name: fint.kontroll.authorization.authorized-org-id
      value: "1 - vigo.no"
    - name: spring.kafka.consumer.group-id
      value: '2 - fint-kontroll-user-service'

  observability:
    metrics:
      enabled: true
      port: "8080"
      path: '/beta/fintlabs-no/actuator/prometheus'
